apiVersion:  apps/v1
kind: Deployment
metadata:
 name: my-nodeapp-deploy
 namespace: ns1

spec:
 replicas : 3
 selector:
    matchLabels:
      app: nodeapp
 template :
   metadata:
    labels :
     app: nodeapp
   spec :
    containers:  
     - name : app1
       image : mostafagheta/my-nodeapp:v1
       ports:
        - containerPort : 3000

